### PR TITLE
Color tweaks

### PR DESCRIPTION
**Pull request by cibersheep**
- Minimal color tweaks
- Bumped PopUps version

### CODE REVIEW

**Comment by cibersheep** [comment]
CI only failed for arm64. Is it a know issue?

**Comment by Flohack74** [comment]
No, but we should try to fix it. ARM64 becomes relevant now. Rest looks ok.

**Comment by cibersheep** [comment]
Is this the error (the test player) https://ci.ubports.com/blue/organizations/jenkins/mediaplayer-app/detail/PR-12/2/pipeline/#step-41-log-1133 ?
 Isn't video playing broken in arm64? Or is it failing for another reason?

**Comment by Flohack74** [comment]
Oh boi! The test crashes... I have no idea how to fix that, can we get @dobey on the case ;)

**Comment by Flohack74** [comment]
@UniversalSuperBox shall we merge this, its kinda cosmetic thing, and for OTA-13 it would be nice if all core Apps have the new splash

**Comment by mariogrip** [comment]
Whaat, i cant reproduce this segfault locally...

**Comment by mariogrip** [comment]
I'll merge since this is just cosmetic and it tests fine on my local arm64 node.

**Comment by mariogrip** [comment]
Ok build is fixed now :) 

ready for QA :D

https://ci.ubports.com/blue/organizations/jenkins/ubports%2Fmediaplayer-app/detail/xenial/4/pipeline

**Comment by cibersheep** [comment]
Plays recorded video with Camera app correctly
E5HD RC

**Comment by Flohack74** [comment]
I dont see the new splash, will try to confirm that I have latest devel...

**Pull request merged**
